"""add file fields to documents

Revision ID: 89200f040922
Revises: fde666ba0d6a
Create Date: 2026-04-27 18:20:15.461959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89200f040922'
down_revision: Union[str, Sequence[str], None] = 'fde666ba0d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('content_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'file_name')
    # ### end Alembic commands ###
