"""add index on document in document chunks table

Revision ID: 97471653da38
Revises: 3f06011d7484
Create Date: 2026-05-12 18:42:58.953486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97471653da38'
down_revision: Union[str, Sequence[str], None] = '3f06011d7484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('start_char', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('end_char', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_column('document_chunks', 'end_char')
    op.drop_column('document_chunks', 'start_char')
    # ### end Alembic commands ###
