"""add job events and remove retry count

Revision ID: f44d1d528ee8
Revises: 89200f040922
Create Date: 2026-05-05 16:56:03.893797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44d1d528ee8'
down_revision: Union[str, Sequence[str], None] = '89200f040922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_jobs', 'retry_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_jobs', sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
